### ISSUE TITLE
Cluster `ServiceAccount` is missing RBAC required for distributed JAX in Kubernetes

### ISSUE THREAD

**Issue by aybchan** [AI-Hypercomputer/xpk#488]
The `k8s` `ServiceAccount` resource (`xpk-sa`) created on [workload creation](https://github.com/AI-Hypercomputer/xpk/blob/v0.8.0/src/xpk/commands/workload.py#L297) appears to be empty. 

The `ServiceAccount` created with [`create_xpk_k8s_service_account`](https://github.com/AI-Hypercomputer/xpk/blob/v0.8.0/src/xpk/core/cluster.py#L316), which is referenced by the `k8s` `JobSet` resource created on workload creation, appears to be an empty `ServiceAccount` with no permissions. 

For distributed JAX `JobSet` workloads the following RBAC configurations of the `ServiceAccount` resource are necessary:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: xpk-sa
    namespace: default
roleRef: 
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```
https://github.com/jax-ml/jax/blob/main/examples/k8s/svc-acct.yaml
